(() => {
  'use strict';

  const KEYS = Object.freeze({
    user:'unitrade_user', users:'unitrade_users', listings:'unitrade_listings', favorites:'unitrade_favorites',
    requests:'unitrade_requests', trades:'unitrade_trade_offers', notifications:'unitrade_notifications',
    recentlyViewed:'unitrade_recently_viewed', theme:'unitrade_theme', settings:'unitrade_settings',
    tourCompleted:'unitrade_tour_completed', karma:'unitrade_karma', impact:'unitrade_impact_metrics',
    lastSession:'unitrade_last_session', searches:'unitrade_recent_searches', lostFound:'unitrade_lost_found',
    vault:'unitrade_vault', fireNotify:'unitrade_fire_notify', rentPlan:'unitrade_rent_plan', compare:'unitrade_compare',
    storageVersion:'unitrade_storage_version'
  });
  const STORAGE_VERSION='commercial_v5_empty';
  const ROUTES=new Set(['home','marketplace','requests','community','services','rent','barter','fair-price','lost-found','starter-kits','fire-sale','vacation-hold','vault','impact','safety','about','contributors','guide']);
  const SERVICE_ROUTES=new Set(['rent','barter','fair-price','lost-found','starter-kits','fire-sale','vacation-hold','vault']);
  const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
  const escapeHTML=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const initials=name=>String(name||'Guest User').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'GU';
  const $=sel=>document.querySelector(sel);
  const $$=sel=>[...document.querySelectorAll(sel)];
  const dateLabel=iso=>{if(!iso)return 'Flexible'; const d=new Date(`${iso}T00:00:00`);return Number.isNaN(d.getTime())?String(iso):d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})};

  const state={
    user:null,users:[],listings:[],favorites:[],requests:[],trades:[],notifications:[],recentlyViewed:[],
    theme:'dark',settings:{compact:false,savedAlerts:true,reducedMotion:false},karma:0,impact:{},searches:[],lostFound:[],
    vault:[],fireNotify:false,rentPlan:null,compare:[],search:'',filterMode:'all',filterCategory:'all',filterCondition:'all',sort:'newest',
    reportType:'lost',tourStep:0
  };

  const TOUR=[
    ['home','view-home','Welcome to UniTrade','This is the product home. Each major workflow lives in its own view so users can focus on one task at a time.','Home','Your campus workspace','The tour keeps the real page visible while explaining it.'],
    ['marketplace','view-marketplace','Marketplace','Browse user-created listings with search, category, condition, transaction mode, proximity and comparison tools.','Marketplace','Discover what students have shared','Listings appear only after users create them.'],
    ['requests','view-requests','Looking For','Post an item request with budget, date, location and preferred transaction mode so other students can respond.','Looking For','Create demand','Requests are stored in your browser until a backend is connected.'],
    ['community','view-community','Community','Campus Karma turns useful actions such as giveaways and responsible exchanges into a visible contribution system.','Community','Build useful reputation','The community area starts empty and grows from your activity.'],
    ['services','view-services','Smart Services','A dedicated utility hub keeps specialized workflows out of the main marketplace.','Services','Focused tools, separate spaces','Choose a service from the cards or quick-access rail.'],
    ['rent','view-rent','Rent & Borrow','Plan temporary access with period, deposit, return date and handover notes.','Rent & Borrow','Use more, own less','Reservation and payment can be moved to the backend later.'],
    ['barter','view-barter','Barter & Trade','Choose one of your listings, select another listing and send a structured offer.','Barter & Trade','Trade with context','Offer history remains linked to your local account.'],
    ['fair-price','view-fair-price','Fair Price','Get a transparent resale estimate using price, age, condition, category and demand inputs.','Fair Price','Price with context','The output is always an estimate, not a guarantee.'],
    ['lost-found','view-lost-found','Lost & Found','Compare lost and found reports using shared keywords, colour, location and context.','Lost & Found','Rank likely matches','A match is a suggestion and still requires human confirmation.'],
    ['starter-kits','view-starter-kits','Starter Kits','Combine your own listings into a useful bundle when several items belong to one student need.','Starter Kits','Turn several items into one decision','The bundle view begins when you have multiple listings.'],
    ['fire-sale','view-fire-sale','Fire Sale','Move a personal listing into a faster handover workflow at the end of a semester.','Fire Sale','Clear a room faster','No pre-filled Fire Sale items appear on a new account.'],
    ['vacation-hold','view-vacation-hold','Vacation Hold','Plan short-term storage and record handover responsibilities before leaving campus.','Vacation Hold','Keep heavy things close','The current page is a planning interface for future secure storage services.'],
    ['vault','view-vault','Digital Vault','Add resources you own or are authorized to share and organize them by subject and semester.','Digital Vault','Keep useful knowledge moving','Secure files and permissions should be server-backed later.'],
    ['impact','view-impact','Campus Impact','See reuse-oriented metrics calculated from the activity you actually create instead of invented community numbers.','Impact','Understand your reuse footprint','Metrics start at zero and grow with your actions.'],
    ['safety','view-safety','Trust & Safety','Review practical handover guidance and use reporting workflows when something feels wrong.','Trust & Safety','Make good choices easier','UniTrade never promises risk-free transactions.'],
    ['about','view-about','About UniTrade','Read the product story, operating model, roadmap and the boundary between browser storage and the future backend.','About','Why the product exists','The About page is a dedicated view rather than part of the homepage.'],
    ['contributors','view-contributors','The Makers','Meet the four people named for the product credits.','Contributors','The people behind UniTrade','Profile buttons remain disabled until real links are provided.'],
    ['guide','view-guide','Product Guide','Download the detailed UniTrade handbook with feature explanations, user flows and visual diagrams.','Product Guide','A deeper reference','The PDF is a product document, not a pitch deck.'],
    ['home','siteHeader','Navigation','Use the primary navigation and feature rail to move between focused views without losing context.','Navigation','One click to a product area','The mobile menu exposes the same destinations.'],
    ['marketplace','newListingBtn','Create a listing','Publishing requires an account so listings are always tied to a real local profile.','Create','Publish your first item','The listing modal is the starting point for your personal catalog.'],
    ['home','heroSearch','Search','Press slash to jump straight to Marketplace search from anywhere outside form fields.','Search','Find by title, category or location','Recent searches are stored locally.'],
    ['home','heroAccountActions','Account actions','From the homepage you can sign in or create an account, then keep building your personal campus workspace.','Account','Your workspace begins with you','No marketplace catalog is seeded for new users.'],
    ['guide','view-guide','Complete','That is the UniTrade product: focused workflows, local persistence, honest safety language and a clean path to a secure backend.','Complete','Start using UniTrade','Use the navigation, command palette or keyboard shortcuts whenever you need them.']
  ];

  const COMMANDS=[
    ['Home','Open the campus workspace','home'],['Marketplace','Browse listings','marketplace'],['Looking For','Post a request','requests'],['Community','Open Karma and community','community'],['Services','Open all utilities','services'],
    ['Rent & Borrow','Plan temporary access','rent'],['Barter & Trade','Create a trade offer','barter'],['Fair Price','Estimate resale value','fair-price'],['Lost & Found','Find likely report matches','lost-found'],['Starter Kits','Bundle your listings','starter-kits'],
    ['Fire Sale','Open semester clear-out','fire-sale'],['Vacation Hold','Plan storage','vacation-hold'],['Digital Vault','Open resources','vault'],['Impact','Open local impact','impact'],['Trust & Safety','Open safety center','safety'],['About','Read about UniTrade','about'],['Contributors','Meet the makers','contributors'],['Product Guide','Read and download the product guide','guide']
  ];

  function saveData(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(err){console.warn('localStorage write failed',err);toast('Local save unavailable','Your browser blocked local storage for this page.','error');return false}}
  function loadData(key,fallback){try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch(err){console.warn('localStorage read failed',err);return fallback}}
  function removeData(key){try{localStorage.removeItem(key)}catch(err){console.warn('localStorage remove failed',err)}}
  function persist(){saveData(KEYS.user,state.user);saveData(KEYS.users,state.users);saveData(KEYS.listings,state.listings);saveData(KEYS.favorites,state.favorites);saveData(KEYS.requests,state.requests);saveData(KEYS.trades,state.trades);saveData(KEYS.notifications,state.notifications);saveData(KEYS.recentlyViewed,state.recentlyViewed);saveData(KEYS.theme,state.theme);saveData(KEYS.settings,state.settings);saveData(KEYS.karma,state.karma);saveData(KEYS.impact,state.impact);saveData(KEYS.searches,state.searches);saveData(KEYS.lostFound,state.lostFound);saveData(KEYS.vault,state.vault);saveData(KEYS.fireNotify,state.fireNotify);saveData(KEYS.rentPlan,state.rentPlan);saveData(KEYS.compare,state.compare);saveData(KEYS.storageVersion,STORAGE_VERSION);saveData(KEYS.lastSession,{at:new Date().toISOString(),route:currentRoute()})}
  function clearLocalData(){Object.values(KEYS).forEach(removeData);location.hash='#home';location.reload()}
  function resetOnVersion(){if(loadData(KEYS.storageVersion,null)!==STORAGE_VERSION){Object.values(KEYS).forEach(removeData);saveData(KEYS.storageVersion,STORAGE_VERSION)}}
  function hydrate(){resetOnVersion();state.user=loadData(KEYS.user,null);state.users=loadData(KEYS.users,[]);state.listings=loadData(KEYS.listings,[]);state.favorites=loadData(KEYS.favorites,[]);state.requests=loadData(KEYS.requests,[]);state.trades=loadData(KEYS.trades,[]);state.notifications=loadData(KEYS.notifications,[]);state.recentlyViewed=loadData(KEYS.recentlyViewed,[]);state.theme=loadData(KEYS.theme,'dark');state.settings={...state.settings,...loadData(KEYS.settings,{})};state.karma=loadData(KEYS.karma,0);state.impact=loadData(KEYS.impact,{});state.searches=loadData(KEYS.searches,[]);state.lostFound=loadData(KEYS.lostFound,[]);state.vault=loadData(KEYS.vault,[]);state.fireNotify=loadData(KEYS.fireNotify,false);state.rentPlan=loadData(KEYS.rentPlan,null);state.compare=loadData(KEYS.compare,[]);applyTheme();applySettings()}

  function toast(title,message='',type='info'){const wrap=document.createElement('div');wrap.className=`toast toast-${type}`;wrap.innerHTML=`<span class="toast-icon">${type==='error'?'!':type==='success'?'✓':'i'}</span><div><strong>${escapeHTML(title)}</strong><small>${escapeHTML(message)}</small></div><button aria-label="Dismiss">×</button>`;$('#toastRegion')?.appendChild(wrap);wrap.querySelector('button')?.addEventListener('click',()=>wrap.remove());setTimeout(()=>wrap.remove(),4200)}
  function addNotification(title,text,unread=true){state.notifications.unshift({id:`n_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,title,text,time:'Just now',unread});state.notifications=state.notifications.slice(0,40);persist();renderNotifications();renderNotificationCount()}
  function renderNotificationCount(){const count=state.notifications.filter(n=>n.unread).length;$('#notificationCount').textContent=count;$('#notificationCount').classList.toggle('hidden',count===0)}
  function renderNotifications(){$('#notificationList').innerHTML=state.notifications.length?state.notifications.map(n=>`<article class="notification-item"><span class="notification-dot ${n.unread?'is-new':''}"></span><div><b>${escapeHTML(n.title)}</b><p>${escapeHTML(n.text)}</p><small>${escapeHTML(n.time||'')}</small></div></article>`).join(''):'<div class="empty-state compact"><h3>No notifications yet</h3><p>New listing saves, help offers and account activity will appear here.</p></div>'}

  function applyTheme(){document.documentElement.dataset.theme=state.theme==='light'?'light':'dark';if($('#themeIcon'))$('#themeIcon').textContent=state.theme==='light'?'☼':'◐'}
  function toggleTheme(){state.theme=state.theme==='light'?'dark':'light';applyTheme();persist();toast(`${state.theme==='light'?'Light':'Dark'} theme enabled`,'Your preference was saved locally.','success')}
  function applySettings(){document.body.classList.toggle('compact-mode',!!state.settings.compact);document.body.classList.toggle('reduced-motion-user',!!state.settings.reducedMotion);if($('#compactCards'))$('#compactCards').checked=!!state.settings.compact;if($('#savedAlerts'))$('#savedAlerts').checked=!!state.settings.savedAlerts;if($('#reducedMotion'))$('#reducedMotion').checked=!!state.settings.reducedMotion}

  function currentRoute(){const raw=(location.hash||'#home').slice(1).split('?')[0];return ROUTES.has(raw)?raw:'home'}
  function routeLabel(route){return ({home:'Home',marketplace:'Marketplace',requests:'Looking For',community:'Community',services:'Services',rent:'Rent & Borrow',barter:'Barter & Trade','fair-price':'Fair Price','lost-found':'Lost & Found','starter-kits':'Starter Kits','fire-sale':'Fire Sale','vacation-hold':'Vacation Hold',vault:'Digital Vault',impact:'Campus Impact',safety:'Trust & Safety',about:'About UniTrade',contributors:'Contributors',guide:'Product Guide'}[route]||'UniTrade')}
  function navigate(route,{target=null,fromTour=false}={}){const safe=ROUTES.has(route)?route:'home';if(currentRoute()!==safe)location.hash=`#${safe}`;renderRoute(safe);setTimeout(()=>{const el=target?$('#'+target):$(`#view-${safe}`);el?.scrollIntoView({behavior:state.settings.reducedMotion?'auto':'smooth',block:target?'center':'start'});if(fromTour&&target)spotlight(el)},90)}
  function renderRoute(route=currentRoute()){$$('.page-view').forEach(v=>v.hidden=v.dataset.view!==route);$$('.desktop-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route||(SERVICE_ROUTES.has(route)&&a.dataset.route==='services')));$$('.feature-rail a').forEach(a=>a.classList.toggle('active',a.dataset.route===route));$$('.mobile-nav-links a').forEach(a=>a.classList.toggle('active',a.dataset.route===route||(SERVICE_ROUTES.has(route)&&a.dataset.route==='services')));if(route==='marketplace')renderListings();if(route==='requests')renderRequests();if(route==='community')renderCommunity();if(route==='impact')renderImpact();if(route==='vault')renderVault();if(route==='starter-kits')renderBundleCards();if(route==='fire-sale')renderFireSale();if(route==='barter'){renderTradeOptions();renderTradeHistory()}if(route==='home')syncHomeCounts();document.title=`${routeLabel(route)} — UniTrade`}
  function initNavigation(){const links=[['home','Home'],['marketplace','Marketplace'],['requests','Looking For'],['community','Community'],['services','Services'],['impact','Impact'],['safety','Safety'],['about','About'],['contributors','Contributors'],['guide','Product Guide'],['rent','Rent & Borrow'],['barter','Barter & Trade'],['fair-price','Fair Price'],['lost-found','Lost & Found'],['starter-kits','Starter Kits'],['fire-sale','Fire Sale'],['vacation-hold','Vacation Hold'],['vault','Digital Vault']];$('#mobileNavLinks').innerHTML=links.map(([r,l])=>`<a href="#${r}" data-route="${r}">${escapeHTML(l)}</a>`).join('');document.addEventListener('click',e=>{const routeEl=e.target.closest('[data-route]');if(routeEl){e.preventDefault();navigate(routeEl.dataset.route);closeMobileNav()}});window.addEventListener('hashchange',()=>renderRoute())}

  function openModal(id,focusSelector){const root=$('#modalRoot');if(!root)return;root.hidden=false;$$('#modalRoot > .modal').forEach(m=>m.hidden=true);const modal=$('#'+id);if(!modal)return;modal.hidden=false;modal.dataset.previousFocus=document.activeElement?.id||'';document.body.classList.add('modal-open');setTimeout(()=>{const focus=focusSelector?modal.querySelector(focusSelector):modal.querySelector('input,button,select,textarea');focus?.focus()},60)}
  function closeModal(){const root=$('#modalRoot');if(!root||root.hidden)return;const active=root.querySelector('.modal:not([hidden])');const previous=active?.dataset.previousFocus;root.hidden=true;document.body.classList.remove('modal-open');$('#tourSpotlight').hidden=true;if(previous&&$('#'+previous))$('#'+previous).focus()}
  function closeCommandPalette(){if($('#commandPalette').hidden)return;$('#commandPalette').hidden=true}
  function openCommandPalette(){closeModal();$('#commandPalette').hidden=false;renderCommands('');setTimeout(()=>$('#paletteInput')?.focus(),40)}
  function openShortcuts(){renderShortcuts();openModal('shortcutsModal')}
  function closeMobileNav(){$('#mobileNav').hidden=true;$('#mobileMenuBtn').setAttribute('aria-expanded','false')}

  function resetFilters(){state.search='';state.filterMode='all';state.filterCategory='all';state.filterCondition='all';state.sort='newest';if($('#globalSearch'))$('#globalSearch').value='';if($('#heroSearch'))$('#heroSearch').value='';if($('#categoryFilter'))$('#categoryFilter').value='all';if($('#conditionFilter'))$('#conditionFilter').value='all';if($('#sortFilter'))$('#sortFilter').value='newest';$$('.filter-select[data-filter-mode]').forEach(x=>x.classList.toggle('active',x.dataset.filterMode==='all'));renderListings()}
  function populateCategories(){const cats=[...new Set(state.listings.map(x=>x.category).filter(Boolean))].sort();if($('#categoryFilter'))$('#categoryFilter').innerHTML='<option value="all">All categories</option>'+cats.map(x=>`<option value="${escapeHTML(x)}">${escapeHTML(x)}</option>`).join('')}
  function visibleListings(){let items=state.listings.slice();const q=state.search.trim().toLowerCase();if(q)items=items.filter(x=>[x.title,x.category,x.description,x.seller,x.hostel,x.mode,...(x.tags||[])].join(' ').toLowerCase().includes(q));if(state.filterMode!=='all')items=items.filter(x=>x.mode===state.filterMode);if(state.filterCategory!=='all')items=items.filter(x=>x.category===state.filterCategory);if(state.filterCondition!=='all')items=items.filter(x=>x.condition===state.filterCondition);if(state.sort==='priceLow')items.sort((a,b)=>(a.price||0)-(b.price||0));else if(state.sort==='nearest')items.sort((a,b)=>(parseInt(a.distance)-parseInt(b.distance)));else if(state.sort==='impact')items.sort((a,b)=>(b.impactWeight||0)-(a.impactWeight||0));else items.sort((a,b)=>String(b.created||'').localeCompare(String(a.created||'')));return items}
  function listingCard(x){const fav=state.favorites.includes(x.id),cmp=state.compare.includes(x.id);return `<article class="listing-card" data-id="${escapeHTML(x.id)}"><div class="listing-visual"><div class="listing-tags"><span class="pill pill-mode">${escapeHTML((x.mode||'buy').replace(/^./,c=>c.toUpperCase()))}</span>${x.legacy?'<span class="pill pill-legacy">Legacy item</span>':''}</div><button class="favorite-btn ${fav?'active':''}" data-favorite="${escapeHTML(x.id)}" aria-label="${fav?'Remove from favorites':'Save item'}">${fav?'♥':'♡'}</button><div class="listing-art tone-${escapeHTML(x.artTone||'cyan')}">${escapeHTML(x.art||'✦')}</div></div><div class="listing-body"><div class="listing-meta"><span>${escapeHTML(x.category||'Other')}</span><span>${escapeHTML(x.distance||'Campus')}</span></div><h3>${escapeHTML(x.title)}</h3><p>${escapeHTML(x.description)}</p><div class="listing-foot"><div class="price">${x.price===0?'Free':money(x.price)}<small>${x.originalPrice?`${money(x.originalPrice)} original`:escapeHTML(x.availability||'Available')}</small></div><div class="listing-actions"><button class="tiny-action" data-listing-action="view" data-id="${escapeHTML(x.id)}">View</button><button class="tiny-action" data-listing-action="share" data-id="${escapeHTML(x.id)}">Share</button><button class="tiny-action" data-listing-action="report" data-id="${escapeHTML(x.id)}">Report</button></div></div><div class="listing-meta listing-meta-bottom"><span>${escapeHTML(x.hostel||'Campus')}</span><span>${escapeHTML(x.condition||'Condition not set')}</span><button class="compare-chip ${cmp?'selected':''}" data-compare-id="${escapeHTML(x.id)}">${cmp?'✓ Comparing':'Compare'}</button></div></div></article>`}
  function renderListings(){const items=visibleListings();$('#searchCount').textContent=`${items.length} ${items.length===1?'listing':'listings'}`;$('#clearSearch').classList.toggle('hidden',!state.search);$('#listingGrid').innerHTML=items.map(listingCard).join('');$('#listingEmpty').hidden=items.length!==0;$('#listingFilterInsight').textContent=state.listings.length?'Adjust filters or search to narrow the results.':'Your marketplace is empty. Create the first listing after signing in.';bindListingActions();$('#compareBtn').disabled=state.compare.length!==2;$('#compareTray').querySelector('span').textContent=state.compare.length?`${state.compare.length} selected for comparison`:'Select up to two items to compare'}
  function bindListingActions(){$$('.favorite-btn').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.favorite)));$$('[data-listing-action="view"]').forEach(b=>b.addEventListener('click',()=>openListing(b.dataset.id)));$$('[data-listing-action="share"]').forEach(b=>b.addEventListener('click',()=>shareListing(b.dataset.id)));$$('[data-listing-action="report"]').forEach(b=>b.addEventListener('click',()=>openReport(b.dataset.id)));$$('[data-compare-id]').forEach(b=>b.addEventListener('click',()=>toggleCompare(b.dataset.compareId)));}
  function toggleFavorite(id){if(!state.user){showLogin();return}const i=state.favorites.indexOf(id);if(i>=0){state.favorites.splice(i,1);toast('Removed from saved items','The listing is no longer in your favorites.')}else{state.favorites.push(id);addNotification('Listing saved','The listing was added to your saved items.');toast('Saved','You can find it again from your profile.','success')}persist();renderListings();renderProfile()}
  function toggleCompare(id){if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else{if(state.compare.length>=2)return toast('Compare limit reached','Choose up to two listings.','error');state.compare.push(id)}persist();renderListings()}
  function openCompare(){const items=state.compare.map(id=>state.listings.find(x=>x.id===id)).filter(Boolean);if(items.length!==2)return toast('Choose two items','Select two listings to compare.','info');$('#detailContent').innerHTML=`<span class="section-kicker">Comparison</span><h2 id="detailTitle">Two campus options, side by side.</h2><div class="impact-detail-grid">${items.map(x=>`<div class="glass-panel impact-card"><span class="section-kicker">${escapeHTML(x.category)}</span><h3>${escapeHTML(x.title)}</h3><ul class="clean-list"><li>Price: ${x.price===0?'Free':money(x.price)}</li><li>Condition: ${escapeHTML(x.condition||'Not specified')}</li><li>Location: ${escapeHTML(x.hostel||'Campus')} · ${escapeHTML(x.distance||'Nearby')}</li><li>Mode: ${escapeHTML(x.mode||'Buy')}</li></ul></div>`).join('')}</div>`;openModal('detailModal')}
  function openListing(id){const x=state.listings.find(v=>v.id===id);if(!x)return;state.recentlyViewed=[id,...state.recentlyViewed.filter(v=>v!==id)].slice(0,10);persist();$('#detailContent').innerHTML=`<span class="section-kicker">${escapeHTML(x.category)} · ${escapeHTML(x.mode)}</span><h2 id="detailTitle">${escapeHTML(x.title)}</h2><p>${escapeHTML(x.description)}</p><div class="impact-detail-grid"><div class="glass-panel impact-card"><span class="section-kicker">Listing details</span><h3>${x.price===0?'Free':money(x.price)}</h3><ul class="clean-list"><li>Condition: ${escapeHTML(x.condition||'Not specified')}</li><li>Availability: ${escapeHTML(x.availability||'Available')}</li><li>Pickup: ${escapeHTML(x.hostel||'Campus')} · ${escapeHTML(x.distance||'Nearby')}</li><li>Seller: ${escapeHTML(x.seller||'Campus member')}</li></ul></div><div class="glass-panel impact-card"><span class="section-kicker">Next step</span><h3>Start a responsible campus conversation.</h3><p>Clarify condition, timing, price, accessories and handover location before completing the exchange.</p><div class="page-actions"><button class="btn btn-primary" id="detailContactBtn">Contact seller</button><button class="btn btn-secondary" id="detailSaveBtn">${state.favorites.includes(x.id)?'Saved':'Save item'}</button></div></div></div>`;openModal('detailModal');$('#detailContactBtn').addEventListener('click',()=>{closeModal();contactSeller(x.id)});$('#detailSaveBtn').addEventListener('click',()=>{toggleFavorite(x.id);closeModal()})}
  function shareListing(id){const x=state.listings.find(v=>v.id===id);if(!x)return;const url=`${location.origin}${location.pathname}#marketplace`;if(navigator.share){navigator.share({title:`${x.title} · UniTrade`,text:`${x.title} · ${x.hostel||'Campus'} · ${x.distance||'Nearby'}`,url}).catch(()=>{})}else if(navigator.clipboard){navigator.clipboard.writeText(url).then(()=>toast('Link copied','Marketplace link copied to your clipboard.','success')).catch(()=>toast('Share unavailable','Copy the page URL manually.','error'))}}
  function contactSeller(id){const x=state.listings.find(v=>v.id===id);if(!x)return;if(!state.user){showLogin();return}addNotification(`Conversation ready · ${x.title}`,'Use the future secure in-app chat flow to continue the exchange.');toast('Conversation started','Keep sensitive contact details out of public listing text.','success')}
  function openReport(id){if(!state.user){showLogin();return}$('#reportForm').dataset.listingId=id;openModal('safetyModal')}

  function renderRequests(){const list=state.requests;$('#requestCount').textContent=list.length;$('#requestList').innerHTML=list.length?list.map(r=>`<article class="request-card"><div class="request-card-top"><span class="pill">${escapeHTML(r.preference)}</span><span class="tiny-label">${escapeHTML(dateLabel(r.date))}</span></div><h3>${escapeHTML(r.item)}</h3><p>${escapeHTML(r.description)}</p><div class="request-tags"><span>${r.budget?`Up to ${money(r.budget)}`:'Budget flexible'}</span><span>${escapeHTML(r.hostel||'Campus-wide')}</span><span>by ${escapeHTML(r.author||'You')}</span></div><button class="btn btn-secondary" data-help-request="${escapeHTML(r.id)}">I can help</button></article>`).join(''):'<div class="empty-state"><h3>No requests yet</h3><p>Once you publish a Looking For request, it will appear here.</p><button class="btn btn-primary" id="emptyRequestBtn">Create a request</button></div>';$$('[data-help-request]').forEach(b=>b.addEventListener('click',()=>{if(!state.user)return showLogin();addNotification('Help offer recorded','Your interest was stored locally for this request.');toast('Thanks for helping','A future secure messaging layer can connect both students.','success')}));$('#emptyRequestBtn')?.addEventListener('click',()=>state.user?openModal('requestModal'):showLogin())}
  function submitRequest(form){if(!state.user){closeModal();return showLogin()}const f=new FormData(form);const req={id:`r_${Date.now()}`,item:String(f.get('item')).trim(),budget:Number(f.get('budget')||0),date:String(f.get('date')||''),hostel:String(f.get('hostel')||'Campus-wide'),preference:String(f.get('preference')),description:String(f.get('description')).trim(),author:state.user.name,created:new Date().toISOString()};if(!req.item||!req.description)return;state.requests.unshift(req);addKarma(5,'Request posted');persist();form.reset();closeModal();renderRequests();renderImpact();toast('Request published','Your Looking For request is now visible.','success')}

  function addKarma(points,reason){state.karma=(Number(state.karma)||0)+Number(points||0);persist();if(points>0)addNotification(`+${points} Karma`,reason,false);renderCommunity()}
  function renderCommunity(){const points=Number(state.karma)||0;const level=points>=1000?'Sustainability Legend':points>=700?'Campus Hero':points>=450?'Reuser':points>0?'Helper':'New member';const next=points<450?450-points:points<700?700-points:points<1000?1000-points:0;$('#karmaCardPoints').textContent=points;$('#karmaLevel').textContent=level;$('#karmaProgressBar').style.width=points?`${Math.min(100,Math.max(5,Math.round((points%250)/2.5)))}%`:'0%';$('#karmaNextText').textContent=next?`${next} points to the next level.`:points?'Top level reached.':'Create a helpful listing or request to start earning Karma.';$('#leaderboard').innerHTML=points&&state.user?`<div class="leader-row"><span>1</span><div><b>${escapeHTML(state.user.name)}</b><small>${escapeHTML(level)}</small></div><strong class="leader-score">${points}</strong></div>`:'<div class="empty-state compact"><h3>No community ranking yet</h3><p>Campus ranking becomes useful after real accounts begin contributing.</p></div>';const metrics=[['Listings',state.listings.length],['Requests',state.requests.length],['Saved items',state.favorites.length],['Vault resources',state.vault.length]];const max=Math.max(...metrics.map(x=>x[1]),1);const host=$('#communityTrendBars');if(host)host.innerHTML=metrics.map(([label,value])=>`<div><span>${label}</span><i><b style="width:${Math.round(value/max*100)}%"></b></i><strong>${value}</strong></div>`).join('')}

  function renderImpact(){const listings=state.listings;const free=listings.filter(x=>x.mode==='free').length;const reused=listings.reduce((n,x)=>n+Number(x.impactWeight||1),0);const savings=listings.reduce((n,x)=>n+Math.max(0,Number(x.originalPrice||0)-Number(x.price||0)),0);const waste=Math.round(reused*0.8);const students=new Set(listings.map(x=>x.seller).filter(Boolean)).size+(state.requests.length?Math.min(state.requests.length,3):0);$('#impactSavings').textContent=money(savings);$('#impactReused').textContent=reused;$('#impactFree').textContent=free;$('#impactWaste').textContent=`${waste} kg`;$('#impactStudents').textContent=students;$('#impactListings').textContent=listings.length;$('#impactOrbValue').textContent=reused;$('#impactHeadline').textContent=reused?`${reused} reuse-weighted listing events are now part of your local UniTrade activity.`:'Your impact story starts at zero and grows from the actions you create.';state.impact={savings,reused,free,waste,students};saveData(KEYS.impact,state.impact)}
  function syncHomeCounts(){const listings=state.listings.length,saved=state.favorites.length,requests=state.requests.length,total=listings+saved+requests;$('#heroListingsCount').textContent=state.user?state.listings.filter(x=>x.seller===state.user.name).length:0;$('#heroSavedCount').textContent=saved;$('#heroWorkspaceCount').textContent=listings;$('#heroWorkspaceStatus').textContent=state.user?'Workspace active':'Waiting for your first action';$('#heroWorkspaceHeadline').textContent=state.user?`Welcome, ${escapeHTML(state.user.name.split(' ')[0])}.`:'Your campus starts here.';$('#heroWorkspaceSub').textContent=state.user?`${listings} listings, ${saved} saved items and ${requests} active requests on this device.`:'Create an account to start listing, saving, requesting and exchanging.';$('#heroActivityText').textContent=total?`${total} saved local interactions`:'No marketplace activity yet';$('#homeCommunityCount').textContent=total;$('#heroStorageState').textContent=state.user?'Active':'Ready';$('#homePulseList').innerHTML=`<div><span>Listings</span><strong>${listings}</strong></div><div><span>Requests</span><strong>${requests}</strong></div><div><span>Saved items</span><strong>${saved}</strong></div>`;$('#heroAvatarStack').innerHTML=state.user?`<span>${escapeHTML(initials(state.user.name))}</span>`:'<span>U</span>';renderImpact()}

  function renderBundleCards(){const owned=state.user?state.listings.filter(x=>x.seller===state.user.name):[];const total=owned.slice(0,4).reduce((n,x)=>n+Number(x.price||0),0);const eligible=Math.min(owned.length,4);const potential=eligible>=2?Math.round(total*.1):0;$('#bundleSourceCount').textContent=owned.length;$('#bundleEligibleCount').textContent=eligible;$('#bundlePotentialSaving').textContent=money(potential);if(owned.length<2){$('#bundleGrid').innerHTML='<div class="empty-state"><h3>Build your first bundle</h3><p>Starter Kits are created from your own listings. Add at least two compatible items in Marketplace first.</p><button class="btn btn-primary" data-route="marketplace">Create a listing</button></div>';return}const group=owned.slice(0,4);const bundle=Math.round(total*.9);$('#bundleGrid').innerHTML=`<article class="bundle-mini"><span class="section-kicker">Your bundle</span><h3>${escapeHTML(group.map(x=>x.title).join(' + '))}</h3><p>${group.map(x=>escapeHTML(x.category||'Other')).join(' · ')}</p><footer><div><b>${money(bundle)}</b><small> · ${money(Math.max(0,total-bundle))} potential bundle saving</small></div><button class="btn btn-secondary" id="saveBundleGenerated">Save bundle idea</button></footer></article>`;$('#saveBundleGenerated').addEventListener('click',()=>{addNotification('Starter Kit saved','Your current listing group was saved as a bundle idea.');toast('Bundle saved','Your Starter Kit idea is stored locally.','success')})}

  function renderFireSale(){const owned=state.user?state.listings.filter(x=>x.seller===state.user.name&&Number(x.price||0)>0):[];$('#fireSaleGrid').innerHTML=owned.length?owned.slice(0,8).map(x=>listingCard({...x,fire:true})).join(''):'<div class="empty-state"><h3>No Fire Sale listings yet</h3><p>Create a listing first. When you are ready for a faster semester-end handover, it can be surfaced here.</p><button class="btn btn-primary" id="fireCreateBtn">Create a listing</button></div>';bindListingActions();$('#fireCreateBtn')?.addEventListener('click',()=>state.user?openModal('listingModal'):showLogin())}

  function renderVault(){const q=($('#vaultSearch')?.value||'').toLowerCase();const active=$('.vault-tags .filter-select.active')?.dataset.vaultFilter||'all';const rows=state.vault.filter(v=>(active==='all'||String(v.access).toLowerCase()===active)&&[v.title,v.subject,v.semester,v.author].join(' ').toLowerCase().includes(q));$('#vaultGrid').innerHTML=rows.length?rows.map(v=>`<article class="vault-card"><div class="doc-mark">▣</div><h3>${escapeHTML(v.title)}</h3><p>${escapeHTML(v.subject)} · ${escapeHTML(v.semester)}</p><footer><span>${escapeHTML(v.access)} · ${escapeHTML(v.author||'You')}</span><button class="text-btn" data-vault-preview="${escapeHTML(v.id)}">Preview →</button></footer></article>`).join(''):'<div class="empty-state"><h3>Your Digital Vault is empty</h3><p>Add notes or resources you own or are authorized to share. Keep the copyright and academic-integrity rules visible.</p><button class="btn btn-primary" id="emptyVaultBtn">Add a resource</button></div>';$$('[data-vault-preview]').forEach(b=>b.addEventListener('click',()=>{const v=state.vault.find(x=>x.id===b.dataset.vaultPreview);if(!v)return;$('#detailContent').innerHTML=`<span class="section-kicker">Digital Vault</span><h2 id="detailTitle">${escapeHTML(v.title)}</h2><p>${escapeHTML(v.subject)} · ${escapeHTML(v.semester)}</p><div class="disclaimer"><b>Sharing note</b><span>${escapeHTML(v.note)}</span></div><p class="mini-note">This workspace stores resource metadata locally. Secure file storage and access control should be connected server-side before distributing real documents.</p>`;openModal('detailModal')}));$('#emptyVaultBtn')?.addEventListener('click',()=>state.user?openModal('vaultModal'):showLogin())}

  function renderTradeOptions(){const mine=$('#tradeMine'),target=$('#tradeTarget');if(!mine||!target)return;const mineItems=state.user?state.listings.filter(x=>x.seller===state.user.name):[];mine.innerHTML=mineItems.length?mineItems.map(x=>`<option value="${escapeHTML(x.id)}">${escapeHTML(x.title)}</option>`).join(''):'<option value="">Sign in and create a listing</option>';target.innerHTML=state.listings.length?state.listings.map(x=>`<option value="${escapeHTML(x.id)}">${escapeHTML(x.title)} · ${escapeHTML(x.hostel||'Campus')}</option>`).join(''):'<option value="">No target listings yet</option>';updateTradeSummary()}
  function updateTradeSummary(){const a=state.listings.find(x=>x.id===$('#tradeMine')?.value),b=state.listings.find(x=>x.id===$('#tradeTarget')?.value);$('#tradeSummary').innerHTML=a&&b?`<span>Offer value</span><strong>${money(a.price)} → ${money(b.price)}</strong>`:'<span>Offer value</span><strong>Choose listings</strong>'}
  function renderTradeHistory(){$('#tradeHistory').innerHTML=state.trades.length?state.trades.map(t=>`<article class="trade-row"><div><b>${escapeHTML(t.mineTitle||'Your item')}</b><small>for ${escapeHTML(t.targetTitle||'Target item')} · ${escapeHTML(t.status||'Sent')}</small></div><span>${escapeHTML(t.date||'')}</span></article>`).join(''):'<div class="empty-state compact"><h3>No trade offers yet</h3><p>Your sent offers will appear here.</p></div>'}

  function submitTrade(){if(!state.user)return showLogin();const mine=state.listings.find(x=>x.id===$('#tradeMine').value),target=state.listings.find(x=>x.id===$('#tradeTarget').value);if(!mine||!target)return toast('Choose two listings','Select your listing and the target listing first.','error');if(mine.id===target.id)return toast('Choose different listings','The target must be different from your own listing.','error');const trade={id:`t_${Date.now()}`,mine:mine.id,target:target.id,mineTitle:mine.title,targetTitle:target.title,message:$('#tradeMessage').value.trim(),status:'Sent',date:new Date().toLocaleDateString('en-IN')};state.trades.unshift(trade);persist();$('#tradeMessage').value='';renderTradeHistory();addNotification('Trade offer sent',`Your offer for ${target.title} was stored locally.`);toast('Trade offer sent','The offer is now in your trade history.','success')}

  function calculateFairPrice(){const f=new FormData($('#fairPriceForm'));const original=Math.max(0,Number(f.get('price')||0)),age=Math.max(0,Number(f.get('age')||0)),condition=String(f.get('condition')),demand=String(f.get('demand')),category=String(f.get('category'));const conditionFactor={Excellent:.8,Good:.68,Fair:.5}[condition]||.6;const ageFactor=Math.max(.25,1-age*.08);const demandFactor={High:1.12,Medium:1,Low:.88}[demand]||1;const mid=Math.max(0,original*conditionFactor*ageFactor*demandFactor);const low=Math.round(mid*.9/10)*10,high=Math.round(mid*1.12/10)*10,confidence=Math.min(93,Math.max(54,Math.round(62+conditionFactor*20-age*3+(demand==='High'?6:0))));$('#fairPriceResult').innerHTML=`<span class="section-kicker">Suggested range</span><h2>${money(low)} – ${money(high)}</h2><div class="confidence-bar"><span style="width:${confidence}%"></span></div><p><b>${confidence}% confidence</b> · Based on ${escapeHTML(category.toLowerCase())}, ${escapeHTML(condition.toLowerCase())} condition, ${age} year${age===1?'':'s'} of age and ${escapeHTML(demand.toLowerCase())} demand.</p><div class="disclaimer"><b>Important</b><span>This is a transparent estimate for pricing decisions, not a guaranteed market value.</span></div>`}

  function similarity(a,b){const tokens=t=>new Set(String(t||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(w=>w.length>2));const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let common=0;A.forEach(x=>{if(B.has(x))common++});return common/(new Set([...A,...B]).size||1)}
  function runLostFoundMatch(){if(!state.user)return showLogin();const f=new FormData($('#lostForm'));const report={id:`lf_${Date.now()}`,type:state.reportType,description:String(f.get('description')),color:String(f.get('color')),location:String(f.get('location')),date:String(f.get('date')||''),category:String(f.get('category')),author:state.user.name};state.lostFound.unshift(report);persist();const matches=state.lostFound.filter(x=>x.id!==report.id).map(x=>{const textA=`${report.description} ${report.color} ${report.location} ${report.category}`;const textB=`${x.description} ${x.color} ${x.location} ${x.category}`;return {...x,score:Math.round(similarity(textA,textB)*100)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,5);$('#matchMeterFill').style.width=`${matches[0]?.score||0}%`;$('#matchExplanation').textContent=matches.length?`Best stored report match: ${matches[0].score}%. Shared words and context contributed to the rank.`:'No stored report was similar enough yet. Keep the report active and review future matches.';$('#matchStack').innerHTML=matches.length?matches.map(x=>`<article class="match-card glass-panel"><div><span class="section-kicker">${escapeHTML(x.type)} report</span><h3>${escapeHTML(x.description)}</h3><p>${escapeHTML(x.location)} · ${escapeHTML(x.category)}</p></div><strong>${x.score}%</strong></article>`).join(''):'<div class="empty-state"><h3>No likely matches yet</h3><p>Your report is saved. A future backend can notify you when new reports create a stronger match.</p></div>';addNotification('Lost & Found report saved','Your report is now stored locally for future matching.');toast('Report saved','Potential matches are suggestions only.','success')}

  async function hashPassword(password){if(window.crypto?.subtle){const data=new TextEncoder().encode(password);const digest=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}let h=0;for(let i=0;i<password.length;i++)h=((h<<5)-h)+password.charCodeAt(i)|0;return `fallback_${Math.abs(h)}`}
  function showLogin(){openModal('loginModal');setAuthMode('login')}
  function showSignup(){openModal('signupModal');setAuthMode('signup')}
  function setAuthMode(mode){$$('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode))}
  function renderProfile(){const u=state.user;$('#navUserName').textContent=u?.name||'Guest';$('#profileBtn').textContent=initials(u?.name);$('#profileBtn').classList.toggle('hidden',!u);$('#guestAuthActions').classList.toggle('hidden',!!u);$('#profileAvatar').textContent=initials(u?.name);$('#profileTitle').textContent=u?.name||'Guest User';$('#profileCollege').textContent=u?`${u.college} · ${u.course}`:'Sign in or create an account to personalise UniTrade';$('#profileKarma').textContent=state.karma;$('#profileListings').textContent=u?state.listings.filter(x=>x.seller===u.name).length:0;$('#profileSaved').textContent=state.favorites.length;$('#heroAccountActions').classList.toggle('hidden',!!u);syncHomeCounts()}

  function renderCommands(query=''){const q=query.toLowerCase().trim();const rows=COMMANDS.filter(x=>!q||x.join(' ').toLowerCase().includes(q));$('#paletteItems').innerHTML=rows.map(x=>`<button class="palette-item" data-command-route="${x[2]}"><b>${escapeHTML(x[0])}</b><small>${escapeHTML(x[1])}</small><span>↗</span></button>`).join('')||'<div class="empty-state compact"><h3>No commands found</h3></div>';$$('[data-command-route]').forEach(b=>b.addEventListener('click',()=>{closeCommandPalette();navigate(b.dataset.commandRoute)}))}
  function renderShortcuts(){const rows=[['/','Focus search'],['Ctrl/Cmd + K','Open command palette'],['T','Start the product tour'],['D','Toggle dark/light theme'],['N','Create a new listing'],['F','Open Marketplace filters'],['H','Home'],['M','Marketplace'],['A','About'],['?','Shortcuts'],['Escape','Close overlay'],['← / →','Move through the tour']];$('#shortcutList').innerHTML=rows.map(r=>`<div class="shortcut-row"><b>${escapeHTML(r[0])}</b><span>${escapeHTML(r[1])}</span></div>`).join('')}

  function updateSignupProgress(){const form=$('#signupForm');if(!form)return;const required=[...form.querySelectorAll('input[required]')];const done=required.filter(i=>i.type==='checkbox' ? i.checked : Boolean(String(i.value).trim())).length;$('#signupProgress').style.width=`${Math.round(done/required.length*100)}%`}
  function validateSignup(form){const f=new FormData(form);const name=String(f.get('name')).trim(),email=String(f.get('email')).trim().toLowerCase(),pass=String(f.get('password')),confirm=String(f.get('confirm'));if(!name||!email||!pass||!confirm||!f.get('college')||!f.get('course')||!f.get('year')||!f.get('hostel'))return 'Complete all required fields.';if(!/^\S+@\S+\.\S+$/.test(email))return 'Enter a valid email address.';if(pass.length<8)return 'Password must be at least 8 characters.';if(pass!==confirm)return 'Passwords do not match.';if(!f.get('agree'))return 'Accept the responsible-use agreement to continue.';if(state.users.some(u=>u.email===email))return 'An account with this email already exists.';return ''}
  function bindForms(){
    $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),email=String(f.get('email')).trim().toLowerCase(),password=String(f.get('password'));const u=state.users.find(x=>x.email===email);if(!u){toast('Account not found','Check the email or create a UniTrade account first.','error');return}const hash=await hashPassword(password);if(hash!==u.passwordHash){toast('Incorrect password','The password does not match this account.','error');return}state.user={id:u.id,name:u.name,email:u.email,college:u.college,course:u.course,year:u.year,hostel:u.hostel,studentId:u.studentId||''};persist();renderProfile();renderCommunity();renderImpact();renderVault();renderBundleCards();renderFireSale();renderTradeOptions();e.currentTarget.reset();closeModal();toast(`Welcome back, ${state.user.name.split(' ')[0]}`,'Your UniTrade workspace is ready.','success')});
    $('#signupForm').addEventListener('input',updateSignupProgress);
    $('#signupForm').addEventListener('submit',async e=>{e.preventDefault();const error=validateSignup(e.currentTarget);if(error){toast('Please check your account details',error,'error');return}const f=new FormData(e.currentTarget),password=String(f.get('password')),email=String(f.get('email')).trim().toLowerCase(),hash=await hashPassword(password);const u={id:`u_${Date.now()}`,name:String(f.get('name')).trim(),email,passwordHash:hash,college:String(f.get('college')).trim(),course:String(f.get('course')).trim(),year:String(f.get('year')).trim(),hostel:String(f.get('hostel')).trim(),studentId:String(f.get('studentId')||'').trim(),created:new Date().toISOString()};state.users.push(u);state.user={id:u.id,name:u.name,email:u.email,college:u.college,course:u.course,year:u.year,hostel:u.hostel,studentId:u.studentId};state.karma=0;persist();renderProfile();renderCommunity();renderImpact();renderVault();renderBundleCards();renderFireSale();renderTradeOptions();e.currentTarget.reset();updateSignupProgress();closeModal();toast('Account created',`Welcome to UniTrade, ${u.name.split(' ')[0]}.`,'success')});
    $$('.password-toggle').forEach(b=>b.addEventListener('click',()=>{const input=b.parentElement.querySelector('input');const show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'Hide':'Show'}));
    $('#forgotBtn').addEventListener('click',()=>toast('Password recovery','Email recovery will be connected when secure backend authentication is added. For this local account, use the same browser and password you created.','info'));
    $$('[data-auth-mode]').forEach(button=>button.addEventListener('click',()=>button.dataset.authMode==='signup'?showSignup():showLogin()));
    $('#switchToSignup').addEventListener('click',()=>showSignup());$('#switchToLogin').addEventListener('click',()=>showLogin());
    $('#listingForm').addEventListener('submit',e=>{e.preventDefault();createListing(e.currentTarget)});
    $('#requestForm').addEventListener('submit',e=>{e.preventDefault();submitRequest(e.currentTarget)});
    $('#reportForm').addEventListener('submit',e=>{e.preventDefault();if(!state.user){closeModal();return showLogin()}const f=new FormData(e.currentTarget);addNotification('Report submitted','Your concern was stored locally and linked to the current listing where possible.');e.currentTarget.reset();closeModal();toast('Report submitted','Thank you for helping keep UniTrade responsible.','success')});
    $('#vaultForm').addEventListener('submit',e=>{e.preventDefault();if(!state.user){closeModal();return showLogin()}const f=new FormData(e.currentTarget);const v={id:`v_${Date.now()}`,title:String(f.get('title')).trim(),subject:String(f.get('subject')).trim(),semester:String(f.get('semester')).trim(),access:String(f.get('access')),note:String(f.get('note')).trim(),author:state.user.name};state.vault.unshift(v);persist();e.currentTarget.reset();closeModal();renderVault();addKarma(5,'Vault resource added');toast('Resource added','Your resource is saved locally.','success')});
  }

  function createListing(form){if(!state.user){closeModal();return showLogin()}const f=new FormData(form);const price=Math.max(0,Number(f.get('price')||0));const original=Math.max(price,Number(f.get('originalPrice')||0));const listing={id:`l_${Date.now()}`,title:String(f.get('title')).trim(),price,originalPrice:original,category:String(f.get('category')),mode:String(f.get('mode')),condition:String(f.get('condition')),hostel:String(f.get('hostel')).trim(),distance:String(f.get('distance')).trim(),description:String(f.get('description')).trim(),seller:state.user.name,sellerInitials:initials(state.user.name),created:new Date().toISOString().slice(0,10),availability:'Available',legacy:false,impactWeight: f.get('mode')==='free'?2:1,art:'✦',artTone:['cyan','violet','green','amber','magenta'][state.listings.length%5],tags:[]};if(!listing.title||!listing.description)return toast('Complete the listing','Add a title and description before publishing.','error');state.listings.unshift(listing);if(!state.favorites.includes(listing.id)){}persist();populateCategories();renderListings();renderProfile();renderImpact();renderCommunity();renderBundleCards();renderFireSale();form.reset();closeModal();navigate('marketplace');addKarma(listing.mode==='free'?20:10,listing.mode==='free'?'Free item shared':'Listing published');toast('Listing published','Your item is now visible in your marketplace.','success')}

  function bindMarketplace(){
    $('#heroSearch').addEventListener('input',e=>{state.search=e.target.value;state.searches=[state.search.trim(),...state.searches.filter(x=>x!==state.search.trim())].filter(Boolean).slice(0,10);persist();navigate('marketplace')});
    $('#globalSearch').addEventListener('input',e=>{state.search=e.target.value;state.searches=[state.search.trim(),...state.searches.filter(x=>x!==state.search.trim())].filter(Boolean).slice(0,10);persist();renderListings()});
    $('#clearSearch').addEventListener('click',()=>{state.search='';$('#globalSearch').value='';$('#heroSearch').value='';renderListings();$('#globalSearch').focus()});
    $$('.filter-select[data-filter-mode]').forEach(b=>b.addEventListener('click',()=>{$$('.filter-select[data-filter-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filterMode=b.dataset.filterMode;renderListings()}));
    $('#categoryFilter').addEventListener('change',e=>{state.filterCategory=e.target.value;renderListings()});$('#conditionFilter').addEventListener('change',e=>{state.filterCondition=e.target.value;renderListings()});$('#sortFilter').addEventListener('change',e=>{state.sort=e.target.value;renderListings()});
    $('#filterFocusBtn').addEventListener('click',()=>$('#filterRow').scrollIntoView({behavior:state.settings.reducedMotion?'auto':'smooth',block:'center'}));$('#resetFiltersBtn').addEventListener('click',resetFilters);$('#resetFiltersEmpty')?.addEventListener('click',resetFilters);$('#compareBtn').addEventListener('click',openCompare);$('#newListingBtn').addEventListener('click',()=>state.user?openModal('listingModal'):showLogin());
    $('#requestPageBtn').addEventListener('click',()=>state.user?openModal('requestModal'):showLogin());$('#freebieBtn').addEventListener('click',()=>{if(!state.user)return showLogin();state.filterMode='free';navigate('marketplace')});
  }

  function bindServices(){
    $('#saveRentPlan').addEventListener('click',()=>{if(!state.user)return showLogin();state.rentPlan={period:$('.tool-option.active')?.dataset.rentPeriod||'daily',returnDate:$('#rentReturnDate').value,deposit:Number($('#rentDeposit').value||0),note:$('#rentNote').value.trim(),updated:new Date().toISOString()};persist();addKarma(3,'Rent plan saved');toast('Rent plan saved','Your plan is stored locally.','success')});
    $$('#rentOptions .tool-option').forEach(b=>b.addEventListener('click',()=>{$$('#rentOptions .tool-option').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
    $('#tradeMine').addEventListener('change',updateTradeSummary);$('#tradeTarget').addEventListener('change',updateTradeSummary);$('#submitTradeBtn').addEventListener('click',submitTrade);
    $('#fairPriceForm').addEventListener('submit',e=>{e.preventDefault();calculateFairPrice()});
    $$('#lostTypeSwitch button').forEach(b=>b.addEventListener('click',()=>{$$('#lostTypeSwitch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.reportType=b.dataset.reportType}));$('#lostForm').addEventListener('submit',e=>{e.preventDefault();runLostFoundMatch()});
    $('#fireNotifyBtn').addEventListener('click',()=>{state.fireNotify=!state.fireNotify;persist();$('#fireNotifyBtn').textContent=state.fireNotify?'Price-drop alerts enabled':'Notify me about price drops';toast(state.fireNotify?'Alerts enabled':'Alerts disabled','Your preference is stored locally.','success')});
    $$('.storage-card [data-storage-action]').forEach(b=>b.addEventListener('click',()=>{if(!state.user)return showLogin();toast('Storage request started',`${b.dataset.storageAction} details are ready to be connected to a secure storage provider.`,'success')}));
  }

  function bindVault(){const search=$('#vaultSearch');search?.addEventListener('input',renderVault);$$('.vault-tags .filter-select').forEach(b=>b.addEventListener('click',()=>{$$('.vault-tags .filter-select').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderVault()}));$('#vaultUploadBtn').addEventListener('click',()=>state.user?openModal('vaultModal'):showLogin())}
  function bindFairPrice(){}
  function bindLostFound(){}
  function bindFireSale(){renderFireSale()}

  function bindGlobal(){
    $('#themeBtn').addEventListener('click',toggleTheme);$('#notificationsBtn').addEventListener('click',()=>{state.notifications=state.notifications.map(n=>({...n,unread:false}));persist();renderNotifications();renderNotificationCount();openModal('notificationModal')});$('#profileBtn').addEventListener('click',()=>{if(state.user)openModal('profileModal');else showLogin()});$('#mobileMenuBtn').addEventListener('click',()=>{$('#mobileNav').hidden=!$('#mobileNav').hidden;$('#mobileMenuBtn').setAttribute('aria-expanded',String(!$('#mobileNav').hidden))});$('#mobileNavClose').addEventListener('click',closeMobileNav);
    $('#navSignInBtn').addEventListener('click',showLogin);$('#navSignUpBtn').addEventListener('click',showSignup);$('#heroSignInBtn').addEventListener('click',showLogin);$('#heroSignUpBtn').addEventListener('click',showSignup);
    $('#settingsBtn').addEventListener('click',()=>{closeModal();openModal('settingsModal')});$('#settingsFooter').addEventListener('click',()=>openModal('settingsModal'));$('#shortcutsBtn').addEventListener('click',openShortcuts);$('#startTourFooter').addEventListener('click',()=>startTour(0));$('#settingsClearBtn').addEventListener('click',()=>{if(confirm('Clear all UniTrade data stored in this browser? Unrelated browser storage will remain untouched.'))clearLocalData()});$('#logoutBtn').addEventListener('click',()=>{state.user=null;persist();closeModal();renderProfile();renderListings();renderRequests();renderCommunity();renderImpact();renderVault();renderTradeOptions();renderTradeHistory();renderBundleCards();renderFireSale();toast('Signed out','Your marketplace data remains saved on this device.','success')});
    $('#editProfileBtn')?.addEventListener('click',()=>toast('Profile editing','Your current profile fields are stored locally. A richer profile editor can be connected without changing the product navigation.','info'));
    $('#paletteInput').addEventListener('input',e=>renderCommands(e.target.value));$('[data-close-palette]').addEventListener('click',closeCommandPalette);document.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]'))closeModal();if(e.target.closest('[data-route]')?.dataset.route==='guide'&&e.target.closest('button'))navigate('guide')});document.addEventListener('keydown',handleKeyboard);
    $('#compactCards').addEventListener('change',e=>{state.settings.compact=e.target.checked;persist();applySettings()});$('#savedAlerts').addEventListener('change',e=>{state.settings.savedAlerts=e.target.checked;persist();applySettings()});$('#reducedMotion').addEventListener('change',e=>{state.settings.reducedMotion=e.target.checked;persist();applySettings();initCanvas(true)});
  }

  function startTour(step=0){state.tourStep=Math.max(0,Math.min(TOUR.length-1,step));saveData(KEYS.tourCompleted,false);const root=$('#modalRoot');root.hidden=false;root.classList.add('tour-mode');document.body.classList.add('modal-open');$('#tourModal').hidden=false;$('#tourSpotlight').hidden=false;renderTour()}
  function endTour(completed=false){saveData(KEYS.tourCompleted,completed);$('#tourSpotlight').hidden=true;$('#modalRoot').classList.remove('tour-mode');closeModal();toast(completed?'Tour completed':'Tour closed',completed?'You can restart it any time from the footer or keyboard shortcut.':'You can restart the product tour whenever you like.','success')}
  function spotlight(el){if(!el)return;const r=el.getBoundingClientRect(),pad=10;const spot=$('#tourSpotlight'),beam=spot?.querySelector('.tour-beam');if(!spot||!beam)return;spot.hidden=false;beam.style.left=`${Math.max(6,r.left-pad)}px`;beam.style.top=`${Math.max(6,r.top-pad)}px`;beam.style.width=`${Math.min(window.innerWidth-r.left+pad,r.width+pad*2)}px`;beam.style.height=`${Math.min(window.innerHeight-r.top+pad,r.height+pad*2)}px`}
  function renderTour(){const t=TOUR[state.tourStep];navigate(t[0],{fromTour:true});$('#tourStepCount').textContent=`Step ${state.tourStep+1} of ${TOUR.length}`;$('#tourTitle').textContent=t[2];$('#tourDescription').textContent=t[3];$('#tourPreviewLabel').textContent=t[4];$('#tourPreviewValue').textContent=t[5];$('#tourPreviewHint').textContent=t[6];$('#tourProgressBar').style.width=`${Math.round((state.tourStep+1)/TOUR.length*100)}%`;$('#tourPrevBtn').disabled=state.tourStep===0;$('#tourNextBtn').textContent=state.tourStep===TOUR.length-1?'Finish →':'Next →';setTimeout(()=>spotlight($('#'+t[1])||$(`#view-${t[0]}`)),120)}
  function bindTour(){
    $('#startTourHero').addEventListener('click',()=>startTour(0));$('#aboutTourBtn')?.addEventListener('click',()=>startTour(0));$('#serviceTourBtn')?.addEventListener('click',()=>startTour(4));$('#tourSkipBtn').addEventListener('click',()=>endTour(false));$('#tourCloseBtn').addEventListener('click',()=>endTour(false));$('#tourPrevBtn').addEventListener('click',()=>{if(state.tourStep>0){state.tourStep--;renderTour()}});$('#tourNextBtn').addEventListener('click',()=>{if(state.tourStep<TOUR.length-1){state.tourStep++;renderTour()}else endTour(true)});window.addEventListener('resize',()=>{if(!$('#tourModal').hidden)spotlight($('#'+TOUR[state.tourStep][1]))});
  }

  function handleKeyboard(e){const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable;if(e.key==='Escape'){if(!$('#commandPalette').hidden){closeCommandPalette();return}if(!$('#modalRoot').hidden){closeModal();return}}if(typing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommandPalette();return}if(e.key==='/'){e.preventDefault();navigate('marketplace');setTimeout(()=>$('#globalSearch')?.focus(),80);return}if(!$('#tourModal').hidden){if(e.key==='ArrowRight'){e.preventDefault();if(state.tourStep<TOUR.length-1){state.tourStep++;renderTour()}else endTour(true)}if(e.key==='ArrowLeft'){e.preventDefault();if(state.tourStep>0){state.tourStep--;renderTour()}}return}const k=e.key.toLowerCase();if(k==='n'){e.preventDefault();state.user?openModal('listingModal'):showLogin();return}if(k==='f'){e.preventDefault();navigate('marketplace');setTimeout(()=>$('#filterFocusBtn')?.focus(),80);return}if(k==='h'){navigate('home');return}if(k==='m'){navigate('marketplace');return}if(k==='a'){navigate('about');return}if(k==='t'){startTour(0);return}if(k==='d'){toggleTheme();return}if(k==='?'){e.preventDefault();openShortcuts()}}

  function initLoader(){const loader=$('#loader'),progress=$('#loaderProgress'),msg=$('#loaderMessage');const messages=['Preparing your campus marketplace','Restoring your local account','Loading your saved workspace','Preparing your feature views','Opening UniTrade'];let i=0,done=false;const hide=()=>{if(done)return;done=true;loader.classList.add('is-hidden');try{sessionStorage.setItem('unitrade_loader_seen_v4','1')}catch{}};$('#skipLoaderBtn')?.addEventListener('click',hide);let seen=false;try{seen=sessionStorage.getItem('unitrade_loader_seen_v4')==='1'}catch{}if(seen||matchMedia('(prefers-reduced-motion: reduce)').matches){hide();return}const timer=setInterval(()=>{msg.textContent=messages[i];progress.style.width=`${Math.round((i+1)/messages.length*100)}%`;i++;if(i>=messages.length){clearInterval(timer);setTimeout(hide,180)}},180);setTimeout(hide,3000)}

  function initCanvas(force=false){const canvas=$('#bgCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');let raf=0,w=0,h=0,dpr=1;const chars='01 88 09 SS 50 10';let cols=[];const resize=()=>{dpr=Math.min(2,window.devicePixelRatio||1);w=window.innerWidth;h=window.innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const step=17;cols=Array.from({length:Math.ceil(w/step)},(_,i)=>({x:i*step,y:Math.random()*-h,speed:0.35+Math.random()*0.95,phase:Math.random()*Math.PI*2}))};resize();window.addEventListener('resize',resize);if((matchMedia('(prefers-reduced-motion: reduce)').matches||state.settings.reducedMotion)&&!force)return;const draw=()=>{ctx.clearRect(0,0,w,h);const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,'rgba(102,111,160,.10)');grad.addColorStop(.42,'rgba(245,182,226,.13)');grad.addColorStop(1,'rgba(22,17,42,.10)');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.font='12px monospace';cols.forEach(c=>{c.y+=c.speed;if(c.y>h+120)c.y=-Math.random()*200;ctx.fillStyle='rgba(255,255,255,.20)';ctx.fillText(chars[Math.floor((c.y/17+c.x)%chars.length)],c.x,c.y);if(Math.random()<.15){ctx.fillStyle='rgba(247,196,234,.28)';ctx.fillText(chars[Math.floor(Math.random()*chars.length)],c.x+5,c.y+14)}});const t=performance.now()/2100;for(let layer=0;layer<3;layer++){ctx.beginPath();for(let x=0;x<=w;x+=14){const y=h*.34+layer*72+Math.sin(x/145+t+layer)*32+Math.sin(x/310-t*1.3)*22;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.strokeStyle=`rgba(${layer===1?'246,176,210':'130,120,210'},${.12-layer*.025})`;ctx.lineWidth=26;ctx.shadowBlur=24;ctx.shadowColor='rgba(242,168,210,.25)';ctx.stroke();ctx.shadowBlur=0}raf=requestAnimationFrame(draw)};cancelAnimationFrame(raf);draw()}
  function initCursor(){if(matchMedia('(pointer:fine)').matches){document.body.classList.add('cursor-ready');document.addEventListener('pointermove',e=>{const g=$('#cursorGlow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}})}}

  function init(){hydrate();initNavigation();populateCategories();renderProfile();renderNotifications();renderNotificationCount();renderListings();renderRequests();renderCommunity();renderImpact();renderVault();renderTradeOptions();renderTradeHistory();renderBundleCards();renderFireSale();bindGlobal();bindForms();bindMarketplace();bindServices();bindVault();bindFairPrice();bindLostFound();bindFireSale();bindTour();initLoader();initCanvas();initCursor();renderRoute();window.addEventListener('resize',()=>{if(!$('#tourModal').hidden)spotlight($('#'+TOUR[state.tourStep][1]))});}
  let booted=false;
  function boot(){if(booted)return;booted=true;try{init()}catch(err){console.error('UniTrade startup error',err);const loader=$('#loader');loader?.classList.add('is-hidden');toast('UniTrade could not finish startup','The page was recovered from a startup error. Please refresh once and try again.','error')}}
  boot();
})();